name: Deploy

on:
  - push
  - workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy for ${{ matrix.folder }}

    strategy:
      matrix:
        folder: [email]

    steps:
      - uses: actions/checkout@v3

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: ${{ matrix.folder }}
